apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-test
  namespace: argocd
spec:
  project: default 
  syncPolicy:
    automated:
      prune: TRUE
      selfHeal: TRUE

  source:
    repoURL: https://github.com/ham3x/Ai-semantic-search
    targetRevision: main          
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default




