apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_DATABASE: "mydb"
  MYSQL_USER: "myuser"
  MYSQL_PASSWORD: "mypassword"
  MYSQL_ROOT_PASSWORD: "myrootpassword"
  DATABASE_URL: "mysql+pymysql://myuser:mypassword@mysql-db:3306/mydb"
