name: test-github-actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3 
      with: 
        username: ${{secrets.ham3x }} 
        password: ${{secrets.ham3x }} 
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}} 
    - run: docker build -t ham3x/AI-SEMANTIC-SEARCH:latest .
    - run: docker build -t ham3x/AI-SEMANTIC-SEARCH:latest .
    - run:  docker build -t ghcr.io/ham3x/AI-SEMANTIC-SEARCH:latest .
    - run: docker push ham3x/AI-SEMANTIC-SEARCH:latest 
    - run: docker push ghcr.io/ham3x/AI-SEMANTIC-SEARCH:latest





