name: test-github-actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3 
      with: 
        username: ham3x
        password: ${{ secrets.DOCKER_PASSWORD }} 
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}} 
    - run: docker build -t ham3x/ai-semantic-search:latest .
    - run: docker build -t ham3x/ai-semantic-search:latest .
    - run:  docker build -t ghcr.io/ham3x/ai-semantic-search:latest .
    - run: docker push ham3x/ai-semantic-search:latest 
    - run: docker push ghcr.io/ham3x/ai-semantic-search:latest





